spring:
  application:
    name: hjj-task-test
  profiles:
    active: dev
  boot:
    admin:
      client:
        url: http://localhost:9005
        instance:
          prefer-ip: true
    

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    httptrace:
      enabled: true
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
#heart:
#  isMaster: true
#  slave:
#    port: 20001