spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/accounts?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 127.0.0.1
    port: 6379
#  main:
#    allow-bean-definition-overriding: true
#  security:
#    user:
#      name: user
#      password: test

server:
  port: 8090
  servlet:
    context-path: /


#分页pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql

#mybatis
mybatis-plus:
  mapper-locations: classpath*:com/cetc10/hjj/task/mapper/*.xml
  type-aliases-package: com.cetc10.hjj.task.entity

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    httptrace:
      enabled: true
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  config: classpath:logback.xml





